### PR TITLE
Made Appealing README.md and updated contributing.md file and more

### LINKED ISSUE #24: Write README.md file with socalify element and contributors too
- Glimpse
image

- Automatically adding contributors to README.md

### LINKED ISSUE #26: Create good looking readme
Create a readme that demonstrates how to use it and looks nice similar to #24

### PR DESCRIPTION
**Pull request by Mitternachtsmond**
**Issue #24 and Issue #26**

## Changes
- Updated the **Contributing.md file** with instructions for new contributors.
- Made the README file to look more engaging.
- Added instructions to **run the project**.
- Added **contributor section** which gets updated automatically.
- Placed the files in a single folder named **src**.

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
The changes looks good but moving the files to an src folder will break the github action that auto deploys it. So the path in the github action file needs to be changed!

**Comment by Mitternachtsmond** [comment]
I have changed the file arrange as it was previously
Please review the other changes

**Comment by mezotv** [comment]
> I have changed the file arrange as it was previously
> Please review the other changes

You could've just change the path in the github action but I guess this works aswell!

**Review by mezotv — APPROVED** [review]
Looks good!

**Pull request merged**
