### PR TITLE
made component responsive

### PR DESCRIPTION
**Pull request by Maaz4324**

### CODE REVIEW

**Review by forgetfulskybro — CHANGES_REQUESTED** [review]
Looks good, think you could do this with the updated version that was added a few minutes ago? Much appreciated.

**Comment by Maaz4324** [comment]
sure

**Comment by Maaz4324** [comment]
I made the changes

**Comment by Maaz4324** [comment]
Please check

**Comment by forgetfulskybro** [comment]
The code you provided doesn't include the latest branch of `json-generator`.

**Pull request merged**
