### PR TITLE
improved ui

### PR DESCRIPTION
**Pull request by CH1NRU5T**
- Made the main containerbox come in center
- Used flexbox for achieving this

image

### CODE REVIEW

**Comment by mezotv** [comment]
Hey, I just reviewed the code and it doesn't seem like a lot has changed the UI is pretty much the exact same with the difference that the dark/light mode icon is now outside of the box which is a change we had removed earlier and you readded that. Since nothing really changed I'm not gonna merge this.

**Comment by CH1NRU5T** [comment]
Oh, so you want the button to be inside the box?

**Comment by mezotv** [comment]
> Oh, so you want the button to be inside the box?

I would like to keep it the way it is currently!

**Comment by CH1NRU5T** [comment]
So, you don't want the main box to be centered?
Or you want the button as it is?
As I can see currently, the button is outside the container but close to it, top-right, also it's position is fixed

**Comment by mezotv** [comment]
> So, you don't want the main box to be centered? Or you want the button as it is? As I can see currently, the button is outside the container but close to it, top-right, also it's position is fixed

The main box already is centered.

**Pull request closed without merging**
