### PR TITLE
Added Footer with social media handles and copyright and resolved other PR conflicts

### PR DESCRIPTION
**Pull request by InquisitiveMe15**
Screenshots of the changes.
image

image

### CODE REVIEW

**Comment by InquisitiveMe15** [comment]
All conflicts resolved :) Kindly merge.

**Comment by InquisitiveMe15** [comment]
If you want me to work on any other feature please let me know. I would be happy to work on that.

**Comment by mezotv** [comment]
Hey @InquisitiveMe15 looks good but would you be able to make it transparent so it looks better on dark and white mode.

**Review by mezotv — CHANGES_REQUESTED** [review]
Hey @InquisitiveMe15 looks good but would you be able to make it transparent so it looks better on dark and white mode.

**Comment by InquisitiveMe15** [comment]
> 

Okay, I will try.

**Comment by mezotv** [comment]
> > 
> 
> Okay, I will try.

I really like this footer you made earlier 
image

**Comment by InquisitiveMe15** [comment]
I changed the opacity of the footer background.
I think now it's looking good :)

image


image

**Comment by InquisitiveMe15** [comment]
> > > 
> > 
> > 
> > Okay, I will try.
> 
> I really like this footer you made earlier image

Thanks!!!

**Comment by mezotv** [comment]
> I changed the opacity of the footer background. I think now it's looking good :)
> 
> image
> 
> image

I would prefer the completely transparent look.

**Comment by InquisitiveMe15** [comment]
> > I changed the opacity of the footer background. I think now it's looking good :)
> > image
> > image
> 
> I would prefer the completely transparent look.

So, in the dark mode you want background of the footer completely dark and the the light mode completely white?

**Comment by mezotv** [comment]
On dark mode completely transparent and on light mode you can keep the little black bar around the text to make it more readable with full opacity @InquisitiveMe15

**Comment by InquisitiveMe15** [comment]
> On dark mode completely transparent and on light mode you can keep the little black bar around the text to make it more readable with full opacity @InquisitiveMe15


Now it is completely transparent (same as body background color)

image


image

**Comment by mezotv** [comment]
Looks good. Thanks alot for contributing!

**Comment by InquisitiveMe15** [comment]
> Looks good. Thanks alot for contributing!

Thank you! 😊

**Comment by mezotv** [comment]
> > Looks good. Thanks alot for contributing!
> 
> Thank you! 😊

I think I merged it too early Would you be able to open another pr with the changes that are missing @InquisitiveMe15

**Comment by InquisitiveMe15** [comment]
> > > Looks good. Thanks alot for contributing!
> > 
> > 
> > Thank you! 😊
> 
> I think I merged it too early Would you be able to open another pr with the changes that are missing @InquisitiveMe15

could you list the changes that you want, I will try to do them and then make a new PR

**Comment by mezotv** [comment]
> > > > Looks good. Thanks alot for contributing!
> > > 
> > > 
> > > Thank you! 😊
> > 
> > 
> > I think I merged it too early Would you be able to open another pr with the changes that are missing @InquisitiveMe15
> 
> could you list the changes that you want, I will try to do them and then make a new PR

You already added them but forgot to push the code

**Comment by InquisitiveMe15** [comment]
> > > > > Looks good. Thanks alot for contributing!
> > > > 
> > > > 
> > > > Thank you! 😊
> > > 
> > > 
> > > I think I merged it too early Would you be able to open another pr with the changes that are missing @InquisitiveMe15
> > 
> > 
> > could you list the changes that you want, I will try to do them and then make a new PR
> 
> You already added them but forgot to push the code

Ohh! My bad

Pushed the code now and created a pull request.
Kindly merge it.

Sorry for inconveniece.

**Pull request merged**
