### PR TITLE
Add a system to remove whitespace from input and import

### LINKED ISSUE #41: Regex Check
Currently, you can add a space to the input and it will count as an entry.

Add a way to check the input and filter if an input is not filled in, like just a space.

### PR DESCRIPTION
**Pull request by GamerCreator1**
Added the ability to check for whitespace to prevent empty questions.

Closes #41

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
Doesn't seem to be working at all. When testing with empty strings no error gets called.

**Comment by GamerCreator1** [comment]
applied a fix, should work as expected now

**Review by mezotv — CHANGES_REQUESTED** [review]
When a string is empty it won't let you add a new input. That works all fine but when you preview/export it just adds an empty string to it.

image

image

**Comment by forgetfulskybro** [comment]
I thought this feature was already made a while back? 
image

**Comment by mezotv** [comment]
Currently not on pc so i will asign this to @forgetfulskybro.

**Review by forgetfulskybro — CHANGES_REQUESTED** [review]
I added a whitespace and it still put an empty string when exporting and it also shows it on the preview. 
image
image

**Comment by GamerCreator1** [comment]
Should I make it if the user input a value here
image
 as an empty should I not accept?

**Comment by mezotv** [comment]
> Should I make it if the user input a value here
> image
> as an empty should I not accept?

Make it so they cant add more input fields till that is non whitespace or empty.

**Review by mezotv — CHANGES_REQUESTED** [review]
Sort of works but there are 2 things. You cant add another field to the useless section even when no whitespace is there.

And when the error message shows the whole text gets moved to the left a bit.

image

**Review by mezotv — APPROVED** [review]
Tested and works. Thanks for contributing!

**Pull request merged**
