### PR TITLE
UI / Accessibility issue style.css

### PR DESCRIPTION
**Pull request by onthegocode**
Fixed UI issue with a blinking line appearing on the dark mode button when clicked.

select

### CODE REVIEW

**Review by onthegocode — COMMENTED** [review]
Added tab Index to dark mode button for better accessibility.

**Comment by mezotv** [comment]
Hey thanks for the pr. I will review the code once im home this could take a few hours though as its currently 5:46am and i get gome at 3:30pm.

**Comment by onthegocode** [comment]
No worries :)

**Comment by mezotv** [comment]
Hey I just testing this and it seems to break the entired UI 

image

**Review by mezotv — CHANGES_REQUESTED** [review]
Hey I just testing this and it seems to break the entired UI.

image

**Comment by onthegocode** [comment]
My mistake I didn't type "button" correctly, strange VScode didn't pick It up.

**Comment by mezotv** [comment]
> My mistake I didn't type "button" correctly, strange VScode didn't pick It up.

Will test once im home. Thanks!

**Comment by forgetfulskybro** [comment]
> > My mistake I didn't type "button" correctly, strange VScode didn't pick It up.
> 
> Will test once im home. Thanks!

I just tested the code out and it seems to work 👍 
image

**Comment by onthegocode** [comment]
Awesome!

**Review by mezotv — APPROVED** [review]
Looks good and works. Thanks for the pr!

**Comment by onthegocode** [comment]
My pleasure let me know if there's any issues that you'd like me to take on.

**Comment by mezotv** [comment]
> My pleasure let me know if there's any issues that you'd like me to take on.

I might got some tomorrow but I'm really tired. If you'd like you can join our discord server so I can hand you the contributor role. The link should be on the site!

**Comment by onthegocode** [comment]
Awesome! Will join the discord.

**Pull request merged**
