### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by onthegocode**
Changing transform translate property to more modern translate property.

### CODE REVIEW

**Review by mezotv — APPROVED** [review]
Looks good. Thanks for your help!

**Comment by onthegocode** [comment]
Happy to help I'm currently working on the issue of adding a confetti animation to the generator button.

**Comment by mezotv** [comment]
> Happy to help I'm currently working on the issue of adding a confetti animation to the generator button. 

I think there is a js library for that.

**Comment by onthegocode** [comment]
Yep, I'm using the bodymovin cdn which is for Lottie files.

**Pull request merged**
