### PR TITLE
feat(responsive): app fully mobile responsive using media queries

### PR DESCRIPTION
**Pull request by HammadKhaan**
Web is now fully responsive on different screen widths as requested in [#9](https://github.com/Would-You-Bot/json-generator/issues/9)
responsive-1
responsive-2
responisve-3
responsive-4
responsive-5

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
Looks good. Would you be able to fix the merge issues though! It maybe best to wait till the footer pr is merged to not have to do this again.

**Comment by HammadKhaan** [comment]
> Looks good. Would you be able to fix the merge issues though! It maybe best to wait till the footer pr is merged to not have to do this again.

@mezotv Done, I have resolved.

**Comment by mezotv** [comment]
Yea we are still waiting on the footer though

**Comment by mezotv** [comment]
The footer is now done so I can merge this. Thanks a lot for the help! Happy hacktoberfest :D

**Review by mezotv — APPROVED** [review]

**Pull request merged**
