### PR TITLE
fix mode toggle btn view on mobile

### LINKED ISSUE #32: [Fix] Dark/Light mobile button
The current dark mode button doesn't look good on mobile maybe hiding the button and adding one into the box looks better on mobile

### PR DESCRIPTION
**Pull request by vikkyava**
Closes #32 

If you don't mind, I would like to suggest a better design for the icon. I have fixed the position on mobile, but I think the icon should be able to change with different modes, like showing the sun, and moon icons for light and dark mode respectively. that way it is much more appealing and we can take out the dark background so it matches with the box. 

Let me know what you think :)

### CODE REVIEW

**Comment by mezotv** [comment]
Hey first of all thanks for the pr. Would you be able to provide a screenshot of the new look. Also your idea sounds with 2 different icons sounds pretty cool!

**Comment by vikkyava** [comment]
Screenshot (2)
Screenshot (3)

Here's a screenshot of what it looks like with different icons in different modes

**Comment by forgetfulskybro** [comment]
That looks very good. Could you commit the changes you did to this PR so I can push it? I noticed you haven't pushed the latest code yet.

**Comment by vikkyava** [comment]
I have committed the changes 👍

**Review by forgetfulskybro — APPROVED** [review]

**Comment by mezotv** [comment]
> I have committed the changes 👍 

Looks good but atleast for me on mobile the icon doesnt change it shows a sun all the time.

**Comment by vikkyava** [comment]
> > I have committed the changes 👍
> 
> Looks good but atleast for me on mobile the icon doesnt change it shows a sun all the time.

Oh, that's probably a bug with the browser. It works on my end just fine for mobile

Screenshot_2022-10-06-22-17-32-069_com android chrome
Screenshot_2022-10-06-22-17-37-673_com android chrome

**Comment by mezotv** [comment]
> > > I have committed the changes 👍
> > 
> > Looks good but atleast for me on mobile the icon doesnt change it shows a sun all the time.
> 
> Oh, that's probably a bug with the browser. It works on my end just fine for mobile
> 
 Yea most likely just my browser thanks for the pr though!

**Pull request merged**
